"""Generate collapsible nav-tree.js."""
from __future__ import annotations

import json

from .tree_data import TREE


def generate_nav_js() -> str:
    nodes = []
    for mod in TREE:
        children = [
            {
                "id": f"{mod['id']}/{c['id']}",
                "title": c["title"],
                "href": f"m/{mod['id']}/{c['id']}.html",
            }
            for c in mod["children"]
        ]
        hub = mod.get("hub")
        nodes.append(
            {
                "id": mod["id"],
                "title": mod["title"],
                "href": f"m/{hub}" if hub else f"m/{mod['id']}/index.html",
                "children": children,
            }
        )
    data = json.dumps(nodes, indent=2)
    return f"""/* Auto-generated by site/tools/generate_tree.py — do not edit by hand */
window.OHAO_NAV_TREE = {data};

(function () {{
  function render() {{
    const mount = document.getElementById("toc-mount");
    if (!mount || !window.OHAO_NAV_TREE) return;
    const page = document.body.dataset.page || "";
    const depth = parseInt(document.body.dataset.depth || "1", 10);
    const cover = depth === 0 ? "index.html" : depth === 1 ? "../index.html" : "../../index.html";
    const map = depth === 0 ? "m/sitemap.html" : depth === 1 ? "sitemap.html" : "../sitemap.html";
    const gloss = depth === 0 ? "m/glossary.html" : depth === 1 ? "glossary.html" : "../glossary.html";

    function hubHref(mod) {{
      if (mod.href.match(/^m\\/[^/]+\\.html$/)) {{
        if (depth === 0) return mod.href;
        if (depth === 1) return mod.href.slice(2);
        return "../" + mod.href.slice(2);
      }}
      if (depth === 0) return mod.href;
      if (depth === 1) return mod.id + "/index.html";
      return "../" + mod.id + "/index.html";
    }}

    function leafHref(chId) {{
      if (depth === 0) return "m/" + chId + ".html";
      if (depth === 1) return chId + ".html";
      const [modId, leaf] = chId.split("/");
      const my = page.split("/")[0];
      return modId === my ? leaf + ".html" : "../" + modId + "/" + leaf + ".html";
    }}

    function isCurrentMod(mod) {{
      return page === mod.id || page === mod.id + "/index" || page.startsWith(mod.id + "/");
    }}

    let html = '<nav class="toc" aria-label="Codebase tree">' +
      '<div class="toc-brand">OHAO · Tree</div>' +
      '<p class="toc-title">Codebase<span>Module · design units</span></p>' +
      '<a href="' + cover + '" data-page="home"><span class="num">00</span>Cover</a>' +
      '<a href="' + map + '"><span class="num">∑</span>Full sitemap</a>';

    for (const mod of window.OHAO_NAV_TREE) {{
      const open = isCurrentMod(mod);
      const short = mod.title.replace(/^\\d+[^·]*·\\s*/, "");
      const n = mod.children ? mod.children.length : 0;
      html += '<details class="toc-branch' + (open ? " is-current" : "") + '"' +
        (open ? " open" : "") + ' data-mod="' + mod.id + '">';
      html += '<summary class="toc-summary">' +
        '<span class="toc-chevron" aria-hidden="true"></span>' +
        '<span class="toc-summary-text">' + short + '</span>' +
        '<span class="toc-count">' + n + '</span></summary>';
      html += '<div class="toc-children">';
      const hubActive = open && (page === mod.id || page === mod.id + "/index") ? " active" : "";
      html += '<a class="toc-hub' + hubActive + '" href="' + hubHref(mod) + '">' +
        '<span class="num">▸</span>Hub</a>';
      for (const ch of mod.children) {{
        const active = page === ch.id ? " active" : "";
        html += '<a class="toc-leaf' + active + '" href="' + leafHref(ch.id) + '">' +
          '<span class="num">·</span>' + ch.title + '</a>';
      }}
      html += '</div></details>';
    }}

    html += '<div class="group">Reference</div>';
    html += '<a href="' + gloss + '"><span class="num">G</span>Glossary</a>';
    html += '<div class="toc-foot">C++20 · Vulkan 1.3<br/>Branches collapsed by default</div></nav>';
    mount.innerHTML = html;
    const active = mount.querySelector("a.active");
    if (active) active.scrollIntoView({{ block: "nearest" }});
  }}

  if (document.readyState === "loading")
    document.addEventListener("DOMContentLoaded", render);
  else render();
}})();
"""
