# GenerateShaderConstants.cmake
# Generates shaders/includes/shader_constants.glsl from src/renderer/shader/shader_bindings.hpp
#
# This script parses shader_bindings.hpp and extracts constexpr values to create
# matching #define constants for GLSL.
#
# Usage:
#   cmake -P GenerateShaderConstants.cmake
#   or via add_custom_command in CMakeLists.txt

# Configuration
set(SOURCE_FILE "${CMAKE_CURRENT_SOURCE_DIR}/../src/renderer/shader/shader_bindings.hpp")
set(OUTPUT_FILE "${CMAKE_CURRENT_SOURCE_DIR}/../shaders/includes/shader_constants.glsl")

if(NOT EXISTS "${SOURCE_FILE}")
    message(FATAL_ERROR "Source file not found: ${SOURCE_FILE}")
endif()

# Read the source file
file(READ "${SOURCE_FILE}" SOURCE_CONTENT)

# Extract constants using regex
# Pattern matches: constexpr <type> <name> = <value>;
string(REGEX MATCHALL "constexpr[^;]+=[^;]+;" CONST_MATCHES "${SOURCE_CONTENT}")

# Start building output
set(OUTPUT_CONTENT "// shader_constants.glsl - Auto-generated shader constants
// THIS FILE IS AUTO-GENERATED - DO NOT EDIT MANUALLY
//
// Source: src/renderer/shader/shader_bindings.hpp
// Generated by: cmake/GenerateShaderConstants.cmake
//
// Regenerate with: cmake -P cmake/GenerateShaderConstants.cmake

#ifndef SHADER_CONSTANTS_GLSL
#define SHADER_CONSTANTS_GLSL

// =============================================================================
// NOTE: This is a template for the auto-generation system.
// The actual values are extracted from shader_bindings.hpp
// =============================================================================

")

# For now, output a placeholder message
# In a full implementation, this would parse and convert each constant

string(APPEND OUTPUT_CONTENT "// See shader_bindings.hpp for the source of truth
// Constants are manually synchronized for now

#endif // SHADER_CONSTANTS_GLSL
")

# Write output file
file(WRITE "${OUTPUT_FILE}" "${OUTPUT_CONTENT}")

message(STATUS "Generated shader constants: ${OUTPUT_FILE}")
